"""Multi-node cluster management commands."""

from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import vm_claim
from .lnet_net import ClusterNet, NetUnavailable, has_passthrough, resolve_net
from .lustre_build import read_staging_meta, staging_status
from .qemu_run import die, is_running, run
from .vm_net import SSH_OPTS, run_ssh, sshpass_ssh_argv
from .vm_owner import resolve_owner_id
from .vm_state import (
    DEFAULT_TARGET,
    EXIT_TIMEOUT,
    EXIT_UNREACHABLE,
    ROOT_PASSWORD,
    SOCKETS,
    SSH_TIMEOUT,
    ClusterInfo,
    ClusterNode,
    ClusterNotFound,
    VMInfo,
    VMNotFound,
    lustre_libdir,
)


def _sudo_prefix() -> list[str]:
    """``["sudo"]`` unless we are already root or VMs need no root here.

    Used for the per-node ``ltvm create`` / ``ltvm destroy`` children so
    they inherit the outer SUDO_USER rather than having a nested sudo
    overwrite it with "root".
    """
    from . import rootless

    return [] if os.geteuid() == 0 or rootless.ready() else ["sudo"]


def parse_node_spec(spec: str) -> ClusterNode:
    """Parse a node spec like 'mgs+mds:myvm:1' or 'oss:myoss:3'.

    Format: roles:vmname[:diskcount]
    """
    parts = spec.split(":")
    if len(parts) < 2:
        die(f"invalid node spec '{spec}': need roles:name[:disks]")

    roles_str = parts[0]
    name = parts[1]
    # Validate the node name shares the same restrictions cmd_create
    # enforces -- spaces or special chars would break /etc/hosts /
    # SSH config / hostname / fc_name= cmdline.
    from .vm_commands import _validate_vm_name

    _validate_vm_name(name)
    if len(parts) > 2:
        try:
            disk_count = int(parts[2])
        except ValueError:
            die(
                f"invalid disk count '{parts[2]}' in spec '{spec}': "
                f"must be a non-negative integer (format: roles:name[:disks])"
            )
    else:
        disk_count = 0

    roles = roles_str.lower().split("+")
    for r in roles:
        if r not in ("mgs", "mds", "oss", "client"):
            die(f"unknown role '{r}' in spec '{spec}'")

    mdt_disks = 0
    ost_disks = 0
    if "mds" in roles:
        mdt_disks = max(disk_count, 1)
    if "oss" in roles:
        ost_disks = max(disk_count, 1)

    return ClusterNode(
        name=name,
        roles=roles,
        mdt_disks=mdt_disks,
        ost_disks=ost_disks,
    )


CLUSTER_BLOCK_BEGIN = "# --- Cluster configuration"
CLUSTER_BLOCK_END = "# --- END cluster configuration"


def generate_local_sh(
    cluster: ClusterInfo,
    net: ClusterNet,
    os_family: str = "rhel",
    fstype: str = "ldiskfs",
) -> str:
    """Generate the cluster block for cfg/local.sh.

    The block goes into the tree's own cfg/local.sh, after each node's
    disk block, rather than replacing the file: the stock file defines
    what every suite reads -- TSTUSR, RUNAS, QUOTA_USERS and the rest --
    with ``${VAR:-default}``, and this block overrides only what the
    cluster decides.

    *net* is required, and deliberately has no default: NETTYPE and
    MGSNID have to name the same net as the lnet.conf deploy writes, and
    a default here would let a caller reintroduce a hardcoded net
    without touching this function.

    ``fstype`` selects the OSD backend.  Only this line changes for
    ZFS: the MDSDEV*/OSTDEV* written above are the *vdevs* ZFS builds
    its pools on (test-framework.sh's mdsvdevname/ostvdevname), and the
    dataset names default to ``$FSNAME-mdt<n>/mdt<n>``.
    """
    if fstype not in ("ldiskfs", "zfs"):
        raise ValueError(f"unsupported fstype: {fstype!r}")
    mgs = cluster.mgs_node()
    mds_list = cluster.mds_nodes()
    oss_list = cluster.oss_nodes()
    client_list = cluster.client_nodes()

    lustre_dir = lustre_libdir(os_family)
    lines = [
        f"{CLUSTER_BLOCK_BEGIN} (generated by ltvm cluster deploy) ---",
        f"# Cluster: {cluster.name}",
        "",
        "FSNAME=lustre",
        f"NETTYPE={net.net_type}",
        "",
        f"LUSTRE={lustre_dir}",
        f"RLUSTRE={lustre_dir}",
        f"RPWD={lustre_dir}/tests",
        "",
    ]

    lines.append(f"mgs_HOST={mgs.name}")
    lines.append(f"MGSNID={net.nid(mgs.name)}")

    combined = mgs.is_mds
    if not combined:
        lines.append("MGSDEV=/dev/vdb")
    lines.append("")

    if mds_list:
        lines.append(f"mds_HOST={mds_list[0].name}")
        total_mdts = sum(n.mdt_disks for n in mds_list)
        lines.append(f"MDSCOUNT={total_mdts}")

        mdt_idx = 1
        for mds_node in mds_list:
            # MDS disks always start at /dev/vdb on the MDS node.  If
            # MGS+MDS share a node (`combined`), no separate MGS disk
            # exists.  If they don't share, the MGS disk lives on the
            # MGS node, not on this MDS node, so no offset is needed
            # here either.
            disk_offset = 1

            for d in range(mds_node.mdt_disks):
                letter = chr(ord("a") + disk_offset + d)
                lines.append(f"MDSDEV{mdt_idx}=/dev/vd{letter}")
                if len(mds_list) > 1:
                    lines.append(
                        f"mds{mdt_idx}_HOST={mds_node.name}",
                    )
                mdt_idx += 1
        lines.append("")

    if oss_list:
        lines.append(f"ost_HOST={oss_list[0].name}")
        total_osts = sum(n.ost_disks for n in oss_list)
        lines.append(f"OSTCOUNT={total_osts}")

        ost_idx = 1
        for oss_node in oss_list:
            disk_offset = 1
            if oss_node.is_mgs and not oss_node.is_mds:
                disk_offset = 2
            if oss_node.is_mds:
                # If this OSS node is also the MDS, OST disks come
                # after the MDT disks.  Note: an OSS+MDS+MGS node has
                # `combined=True` (mgs.is_mds is True for it), so the
                # extra-MGS-disk offset only applies in the standalone
                # MGS case which lives on a different node entirely.
                disk_offset = 1 + oss_node.mdt_disks

            for d in range(oss_node.ost_disks):
                letter = chr(ord("a") + disk_offset + d)
                lines.append(f"OSTDEV{ost_idx}=/dev/vd{letter}")
                if len(oss_list) > 1:
                    lines.append(
                        f"ost{ost_idx}_HOST={oss_node.name}",
                    )
                ost_idx += 1
        lines.append("")

    if client_list:
        client_names = ",".join(n.name for n in client_list)
        lines.append(f"CLIENTS={client_names}")
        # RCLIENTS is the variable the test framework actually reads.
        #
        # init_clients_lists() (test-framework.sh, called unconditionally
        # from init_logging()) rebuilds CLIENTS *from* RCLIENTS:
        #
        #     clients="$SINGLECLIENT $HOSTNAME $RCLIENTS"
        #     export CLIENTS=$(comma_list $clients)
        #
        # so a CLIENTS= set here and nothing else is overwritten with
        # just the local node, and every remote client silently drops
        # out.  Multi-client suites (sanityn, parallel-scale,
        # recovery-*-scale) then run green against one client while
        # appearing to have used the whole cluster.
        #
        # Tests are driven from the first client, which is the node
        # init_clients_lists() treats as local, so the remote set is
        # clients[1:].  Space-separated to match what hostlist_expand()
        # and the rest of the framework expect.
        rclients = [n.name for n in client_list[1:]]
        if rclients:
            lines.append('RCLIENTS="{}"'.format(" ".join(rclients)))
    lines.append("")

    lines.append(f"FSTYPE={fstype}")
    lines.append("OSTSEQWIDTH=${OSTSEQWIDTH:-0x20000}")
    lines.append("")

    lines.append("LCTL=/usr/sbin/lctl")
    lines.append("LFS=/usr/bin/lfs")
    lines.append("")

    lines.append('PDSH="pdsh -S -Rssh -w"')
    lines.append("LOAD_MODULES_REMOTE=true")
    lines.append("MOUNT=/mnt/lustre")
    lines.append("MOUNT1=${MOUNT1:-$MOUNT}")
    lines.append("MOUNT2=/mnt/lustre2")
    lines.append("MOUNT3=${MOUNT3:-${MOUNT}3}")
    lines.append("DIR=${DIR:-$MOUNT}")
    lines.append("DIR1=${DIR1:-$MOUNT1}")
    lines.append("DIR2=${DIR2:-$MOUNT2}")
    lines.append("DIR3=${DIR3:-$MOUNT3}")
    lines.append("")

    # Tests run from a client, which has no disk block of its own, and
    # it is the client's stop() that must remove each target's dm-flakey
    # mapper for a reformatting suite to reach the raw device.
    lines.append("CLEANUP_DM_DEV=true")
    lines.append(f"{CLUSTER_BLOCK_END} ---")

    return "\n".join(lines) + "\n"


# ── cluster commands ─────────────────────────────────────


def _create_one_node(
    node: ClusterNode,
    vcpus: int,
    mem: int | None,
    os_target: str | None = None,
    arch: str | None = None,
    disk_size: str | None = None,
    root_size: str | None = None,
    nics: list[str] | None = None,
    kernel_args: str = "",
    owner_id: str | None = None,
    wait_seconds: int = 0,
    kernel: str | None = None,
    variant: str = "base",
) -> tuple[str, int, str]:
    """Create a single cluster VM via ltvm subprocess.

    Returns (node_name, returncode, combined_output).
    Running via subprocess avoids threading issues with shared print/state
    inside cmd_create, and lets all nodes boot concurrently.

    `mem=None` means "let the inner cmd_create resolve from the target's
    default_mem", so cluster nodes inherit the per-target memory default
    instead of being silently overridden by a hardcoded constant in the
    cluster CLI parser.

    `nics` is an optional list of `--nic` spec strings that get applied
    uniformly to every node.  Validation of each spec (including the
    reserved-type rejection for softroce/passthrough) happens inside
    the child `ltvm create`, so bad specs surface per-node with the
    follow-up-issue hint the single-node path prints.
    """
    mgs_disk = 1 if (node.is_mgs and not node.is_mds) else 0
    # No `sudo` prefix when already root: cluster create requires root, so
    # a nested sudo would reset SUDO_USER to "root" in the child and the
    # child's ~/.ssh bookkeeping would target root's home instead of the
    # invoking user's.  (On macOS that is a hard failure -- root's home is
    # /var/root and /root is on the read-only system volume.)
    cmd = _sudo_prefix() + [
        "ltvm",
        "create",
        node.name,
        "--vcpus",
        str(vcpus),
    ]
    if mem is not None:
        cmd += ["--mem", str(mem)]
    if os_target:
        cmd += ["--target", os_target]
    if arch:
        cmd += ["--arch", arch]
    if kernel:
        cmd += ["--kernel", kernel]
    if variant != "base":
        cmd += ["--variant", variant]
    if disk_size:
        cmd += ["--disk-size", disk_size]
    if root_size:
        cmd += ["--root-size", root_size]
    if owner_id:
        # Pass the cluster parent's resolved value explicitly so all members
        # share one owner even though each child has a different process PID.
        cmd += ["--owner-id", owner_id]
    # Always pass both counts, including zero.  Omitting a flag lets
    # `ltvm create`'s defaults (1 MDT, 2 OST) apply, so an oss-only
    # node silently gained an MDT-slot disk ahead of its OSTs -- which
    # shifts every /dev/vd* letter past what generate_local_sh computes
    # (its disk_offset assumes exactly the disks the role asked for).
    # The result mounted fine, because the backing files are
    # identical-size scratch images, while OSTDEV1 pointed at the
    # spurious disk and the last real OST disk went unused.
    cmd += ["--mdt-disks", str(node.mdt_disks + mgs_disk)]
    cmd += ["--ost-disks", str(node.ost_disks)]
    for nic in nics or []:
        cmd += ["--nic", nic]
    if kernel_args:
        # One argv word, so a value starting with '-' is not an option.
        cmd += [f"--kernel-args={kernel_args}"]
    if wait_seconds:
        cmd += ["--wait", str(wait_seconds)]

    try:
        r = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=_node_create_timeout() + wait_seconds,
        )
    except subprocess.TimeoutExpired as e:
        # See _write_cluster_local_sh: don't propagate out of the parallel
        # executor; report the failure via the (name, rc, output) tuple
        # so the cluster create driver can summarise per-node failures.
        return node.name, 1, f"create timed out after {e.timeout}s"
    combined = r.stdout
    if r.stderr:
        combined = combined + r.stderr if combined else r.stderr
    return node.name, r.returncode, combined.rstrip("\n")


# Headroom over the inner `ltvm create`'s own wait-for-SSH budget:
# cold boot, disk creation and first-boot work all happen outside it.
# 270 keeps the historical 300s total at the default SSH_TIMEOUT of 30.
_NODE_CREATE_HEADROOM = 270


def _node_create_timeout() -> int:
    """Wall-clock budget for one node's child `ltvm create`.

    Derived from SSH_TIMEOUT rather than hardcoded, because
    LTVM_SSH_TIMEOUT exists precisely so an operator can raise the
    wait-for-SSH budget for a TCG guest ("Cross-arch (TCG) boots are
    5-20x slower", vm_state) -- and a fixed 300s here turned that
    remedy into a guaranteed failure: every child was SIGKILLed at 300s
    mid-boot and the cleanup loop then destroyed the whole cluster,
    with "create timed out after 300s" as the only explanation.
    """
    return max(300, SSH_TIMEOUT + _NODE_CREATE_HEADROOM)


def _print_cluster_plan(
    cluster_name: str,
    node_specs: list[ClusterNode],
    *,
    vcpus: int,
    mem: int | None,
    os_target: str | None,
    arch: str | None,
    kernel: str | None,
    variant: str,
    disk_size: str | None,
    root_size: str | None,
    nics: list[str],
    kernel_args: str,
    owner_id: str | None,
) -> None:
    """Report what `cluster create` would do, for --dry-run.

    Per-node IPs are not shown: each node's `ltvm create` claims one
    under a lock, so there is no honest answer without claiming them.
    """
    print(
        f"Would create cluster '{cluster_name}' with {len(node_specs)} nodes:"
    )
    for node in node_specs:
        disks = []
        if node.mdt_disks:
            disks.append(f"{node.mdt_disks} MDT")
        if node.ost_disks:
            disks.append(f"{node.ost_disks} OST")
        print(
            f"  {node.name:<20} roles={'+'.join(node.roles):<16} "
            f"disks={', '.join(disks) or 'none'}"
        )
    mem_desc = f"{mem} MB" if mem is not None else "target default"
    arch_desc = f" arch={arch}" if arch else ""
    print("Applied to every node:")
    variant_desc = f" variant={variant}" if variant != "base" else ""
    print(f"  target:  {os_target or 'default'}{arch_desc}{variant_desc}")
    print(f"  kernel:  {kernel or 'target default'}")
    print(f"  cpu/mem: {vcpus} vcpus, {mem_desc}")
    if disk_size:
        print(f"  disk:    {disk_size} each")
    if root_size:
        print(f"  root:    {root_size} each")
    if nics:
        print(f"  nics:    eth0 (mgmt) + {', '.join(nics)}")
    if kernel_args:
        print(f"  cmdline: + {kernel_args}")
    print(f"  owner:   {owner_id}")
    print("Nothing was written.  Re-run without --dry-run to create it.")


def cmd_cluster_create(args: argparse.Namespace) -> None:
    cluster_name = args.name
    # Cluster name flows into filesystem paths (SOCKETS/<name>.cluster)
    # so it needs the same character whitelist as VM names.
    from .vm_commands import _validate_kernel_args, _validate_vm_name

    _validate_vm_name(cluster_name)
    record = SOCKETS / f"{cluster_name}.cluster"
    if record.exists():
        try:
            orphaned = ClusterInfo.load(cluster_name).orphaned()
        except ClusterNotFound:
            orphaned = None
        except (RuntimeError, ValueError):
            orphaned = False
        if orphaned is False:
            die(f"cluster '{cluster_name}' already exists")
        if orphaned:
            record.unlink(missing_ok=True)
            print(
                f"removed stale cluster record {cluster_name}: "
                f"all its VMs are gone"
            )

    node_specs = [parse_node_spec(s) for s in args.nodes]

    # Refuse a spec that names the same node twice.  Nothing checked,
    # so `cluster create co2 mgs+mds:co2-a:1 oss:co2-a:3` launched two
    # concurrent `ltvm create co2-a` subprocesses racing on one .info,
    # overlay and TAP -- or the loser adopted the winner and reported
    # success.  The saved ClusterInfo then carried the same host twice
    # with contradictory disk roles, and generate_local_sh assigned it
    # MDSDEV and OSTDEV letters from two different disk_offset
    # computations, pointing at overlapping devices.
    seen_names: set[str] = set()
    dupes: set[str] = set()
    for n in node_specs:
        if n.name in seen_names:
            dupes.add(n.name)
        seen_names.add(n.name)
    if dupes:
        die(
            f"node name(s) listed more than once: "
            f"{', '.join(sorted(dupes))}\n"
            f"Each node in a cluster needs its own name."
        )

    # Refuse to build a cluster on top of VMs that already exist.
    # `ltvm create` is idempotent -- _handle_existing_vm starts a
    # stopped VM and exits 0 -- so without this check the cluster
    # silently adopts them.  That matters because the failure path
    # below destroys every name in node_specs: one node failing to
    # come up would delete a pre-existing VM (overlay and data disks
    # included) that this command never created.  `cluster destroy`
    # would do the same later.  Adopting is also wrong on its own
    # terms, since an existing VM won't have the disk layout the role
    # implies.
    taken = [
        n.name for n in node_specs if (SOCKETS / f"{n.name}.info").exists()
    ]
    if taken:
        die(
            f"VM(s) already exist: {', '.join(taken)}\n"
            f"cluster create would adopt them, and would destroy them "
            f"if another node failed.\n"
            f"Destroy them first, or pick different node names."
        )

    mgs_count = sum(1 for n in node_specs if n.is_mgs)
    if mgs_count == 0:
        die("cluster needs at least one node with mgs role")
    if mgs_count > 1:
        die("cluster can only have one MGS node")

    if not any(n.is_mds for n in node_specs):
        die("cluster needs at least one node with mds role")

    vcpus = args.vcpus
    mem = args.mem
    os_target = getattr(args, "os", None)
    arch = getattr(args, "arch", None)
    kernel = getattr(args, "kernel", None)
    variant = getattr(args, "variant", None) or "base"
    disk_size = getattr(args, "disk_size", None)
    root_size = getattr(args, "root_size", None)
    # Multi-NIC: same list of --nic specs applies to every node in the
    # cluster.  The CLI layer (cli.py::cmd_cluster) collects them into
    # args.nic; older call sites that don't know about --nic land here
    # with the attr unset, in which case we pass an empty list through.
    nics: list[str] = list(getattr(args, "nic", None) or [])
    kernel_args = _validate_kernel_args(getattr(args, "kernel_args", None))
    wait_seconds: int = getattr(args, "wait", 0)
    try:
        owner_id = resolve_owner_id(getattr(args, "owner_id", None))
    except ValueError as e:
        die(str(e))

    if getattr(args, "dry_run", False):
        # Everything above is validation and reads -- name rules,
        # duplicate node names, already-taken VMs, the mgs/mds role
        # rules, owner resolution.  The first thing written is a node,
        # created by the pool below.
        _print_cluster_plan(
            cluster_name,
            node_specs,
            vcpus=vcpus,
            mem=mem,
            os_target=os_target,
            arch=arch,
            kernel=kernel,
            variant=variant,
            disk_size=disk_size,
            root_size=root_size,
            nics=nics,
            kernel_args=kernel_args,
            owner_id=owner_id,
        )
        return

    print(f"=== Creating cluster '{cluster_name}' ===")
    if os_target:
        print(f"    Target: {os_target}{(' arch=' + arch) if arch else ''}")
    if kernel:
        print(f"    Kernel: {kernel}")
    if variant != "base":
        print(f"    Variant: {variant}")
    print(f"    Creating {len(node_specs)} nodes in parallel...")

    failed = []
    with ThreadPoolExecutor(max_workers=len(node_specs)) as executor:
        futures = {
            executor.submit(
                _create_one_node,
                node,
                vcpus,
                mem,
                os_target,
                arch,
                disk_size,
                root_size,
                nics,
                kernel_args,
                owner_id,
                wait_seconds=wait_seconds,
                kernel=kernel,
                variant=variant,
            ): node
            for node in node_specs
        }
        for future in as_completed(futures):
            node = futures[future]
            try:
                name, rc, output = future.result()
            except Exception as e:
                # Don't let one node's exception (e.g. TimeoutExpired
                # from the inner subprocess) abandon the remaining
                # futures.  Mark this one as failed and keep
                # collecting -- the cleanup loop below needs an
                # accurate `failed` list.
                name = node.name
                rc = -1
                output = f"exception: {type(e).__name__}: {e}"
            if rc != 0:
                print(f"\n--- {name}: FAILED (rc={rc}) ---\n{output}")
                failed.append(name)
            else:
                print(f"  {name}: up")

    if failed:
        # Clean up ALL nodes, including the failed ones.  A failed
        # `ltvm create` may have already created the TAP, overlay,
        # and .info file before erroring out (e.g. SSH wait timed out
        # so the rollback in cmd_create couldn't run).  `ltvm destroy`
        # is idempotent on missing VMs, so it's safe to call on every
        # node and necessary to avoid leaking partial state.
        for node in node_specs:
            r = subprocess.run(
                _sudo_prefix() + ["ltvm", "destroy", node.name],
                capture_output=True,
            )
            if r.returncode != 0:
                print(
                    f"warning: failed to destroy VM '{node.name}' during cleanup",
                    file=sys.stderr,
                )
        die(f"vm create failed for: {', '.join(failed)}")

    # Load IPs now that all VMs are running
    for node in node_specs:
        vm = VMInfo.load(node.name)
        node.ip = vm.ip

    cluster = ClusterInfo(
        name=cluster_name,
        owner_id=owner_id,
        nodes=[
            {
                "name": n.name,
                "roles": n.roles,
                "mdt_disks": n.mdt_disks,
                "ost_disks": n.ost_disks,
                "ip": n.ip,
            }
            for n in node_specs
        ],
    )
    cluster.save()

    print(f"\n=== Cluster '{cluster_name}' created ===")
    print(f"  owner: {owner_id}")
    for n in node_specs:
        print(f"  {n.name:<20} {n.ip:<18} {'+'.join(n.roles)}")
    print(
        f"\nNext: ltvm cluster deploy {cluster_name} "
        f"--build /path/to/lustre-release [--mount]"
    )


def _deploy_one_node(
    node_name: str,
    lustre_tree: str | Path,
    os_family: str = "rhel",
    zfs_staging: Path | None = None,
) -> tuple[str, int, str]:
    """Deploy Lustre to one cluster node.

    Returns (node_name, returncode, output_message).

    `lustre_tree` is the source tree the cluster's `--build` was
    pointed at; it determines where the per-tree staging dir lives.
    """
    from ltvm_pkg.deploy import deploy_to_vm
    from ltvm_pkg.lustre_build import staging_path as _staging_path

    vm = VMInfo.load(node_name)
    if not vm.os_id:
        raise RuntimeError(f"VM '{vm.name}' has no os_id; recreate it")
    target = vm.os_id
    # Pass vm.arch + kernel so the staging dir matches what
    # build-lustre wrote.  Staging is keyed per-kernel so two kernels'
    # userland can coexist under one lustre tree.
    vm_arch = vm.arch
    deploy_kernel: str | None = None
    if vm.kernel:
        vm_kernel_name = Path(vm.kernel).parent.name
        if vm_kernel_name:
            deploy_kernel = vm_kernel_name
    if deploy_kernel is None:
        return (
            node_name,
            1,
            f"cannot resolve kernel for {node_name}: vm.kernel is unset",
        )
    staging = _staging_path(
        lustre_tree,
        target,
        arch=vm_arch,
        kernel=deploy_kernel,
        variant=vm.variant,
    )
    try:
        # No fstype here: the cluster block written further down
        # (generate_local_sh) sets FSTYPE for every node, after anything
        # written here.
        deploy_to_vm(vm, staging, os_family=os_family, zfs_staging=zfs_staging)
        return node_name, 0, "ok"
    except RuntimeError as e:
        return node_name, 1, str(e)


def _write_cluster_local_sh(
    node_name: str,
    node_ip: str,
    local_sh: str,
    ssh_opts: list[str],
    os_family: str = "rhel",
) -> tuple[str, int, str]:
    """Put the cluster block into a node's cfg/local.sh.

    Returns (node_name, returncode, output).
    """
    from ltvm_pkg.deploy import splice_local_sh_block

    lustre_dir = lustre_libdir(os_family)
    cfg_path = f"{lustre_dir}/tests/cfg/local.sh"
    script = (
        f"mkdir -p {lustre_dir}/tests/cfg && t=$(mktemp) && cat > $t && "
        + splice_local_sh_block(
            cfg_path, "$t", CLUSTER_BLOCK_BEGIN, CLUSTER_BLOCK_END
        )
        + "; rc=$?; rm -f $t; exit $rc"
    )
    try:
        r = subprocess.run(
            sshpass_ssh_argv(node_ip, script),
            input=local_sh,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except subprocess.TimeoutExpired as e:
        # Don't propagate out of the parallel executor; the caller checks
        # the returncode field and reports per-node failures.  Without
        # this catch, one stalled node tracebacks out of future.result()
        # and aborts the cluster config rollout mid-flight.
        return node_name, 1, f"timed out after {e.timeout}s writing {cfg_path}"
    combined = r.stdout
    if r.stderr:
        combined = combined + r.stderr if combined else r.stderr
    return node_name, r.returncode, combined.rstrip("\n")


def _write_cluster_cfg(
    node_name: str,
    node_ip: str,
    cfg_name: str,
    content: str,
    ssh_opts: list[str],
    os_family: str = "rhel",
) -> tuple[str, int, str]:
    """Write an auster cfg file to the standard test location on a node.

    *cfg_name* is the profile name without the ``.sh`` suffix; the file
    lands at ``<lustre libdir>/tests/cfg/<cfg_name>.sh``.

    Returns (node_name, returncode, output).
    """
    lustre_dir = lustre_libdir(os_family)
    cfg_path = f"{lustre_dir}/tests/cfg/{cfg_name}.sh"
    try:
        r = subprocess.run(
            sshpass_ssh_argv(
                node_ip,
                f"mkdir -p {lustre_dir}/tests/cfg && cat > {cfg_path}",
            ),
            input=content,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except subprocess.TimeoutExpired as e:
        # See _write_cluster_local_sh.
        return node_name, 1, f"timed out after {e.timeout}s writing {cfg_path}"
    combined = r.stdout
    if r.stderr:
        combined = combined + r.stderr if combined else r.stderr
    return node_name, r.returncode, combined.rstrip("\n")


LNET_CONF_PATH = "/etc/modprobe.d/lnet.conf"


def _write_lnet_conf(
    node_name: str,
    node_ip: str,
    content: str,
) -> tuple[str, int, str]:
    """Overwrite ``/etc/modprobe.d/lnet.conf`` on one node.

    Written next to ``local.sh`` and from the same resolved net: the two
    files name the same network or the node cannot mount.  Overwriting
    is deliberate -- ``rc.local`` only composes an lnet.conf when none
    exists, so what deploy writes here is what the node keeps across
    reboots.

    Returns (node_name, returncode, output).
    """
    try:
        r = subprocess.run(
            sshpass_ssh_argv(node_ip, f"cat > {LNET_CONF_PATH}"),
            input=content,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except subprocess.TimeoutExpired as e:
        return (
            node_name,
            1,
            f"timed out after {e.timeout}s writing {LNET_CONF_PATH}",
        )
    combined = r.stdout
    if r.stderr:
        combined = combined + r.stderr if combined else r.stderr
    return node_name, r.returncode, combined.rstrip("\n")


def stale_lnet_check(net_type: str) -> str:
    """Shell that drops a running LNet configured for another net.

    ``lnet.conf`` is read by ``modprobe``, so a net change does nothing
    to an LNet already loaded: the node keeps serving the old net while
    both config files name the new one, which is the drift this whole
    path exists to remove.  A node with no LNet loaded, or one already
    on the right net, is left alone -- so a same-net redeploy does not
    disturb a mounted filesystem.
    """
    return (
        # No LNet loaded: nothing to drop.
        "if ! lsmod | grep -q '^lnet '; then exit 0; fi; "
        # 0@lo is on every node and belongs to no net.
        "nids=$(lctl list_nids 2>/dev/null | grep -v '@lo$'); "
        # Every NID already on the target net: leave it running.
        "if [ -n \"$nids\" ] && "
        f"! printf '%s\\n' \"$nids\" | grep -qv '@{net_type}[0-9]*$'; "
        "then exit 0; fi; "
        "lustre_rmmod"
    )


def _drop_stale_lnet(
    node_name: str,
    node_ip: str,
    net_type: str,
) -> tuple[str, int, str]:
    """Unload an LNet still running the net the node just moved off."""
    try:
        r = run_ssh(node_ip, stale_lnet_check(net_type), timeout=120)
    except subprocess.TimeoutExpired as e:
        return node_name, 1, f"timed out after {e.timeout}s unloading LNet"
    if r.returncode != 0:
        return (
            node_name,
            r.returncode,
            f"{(r.stderr or r.stdout or '').strip()}\n"
            f"  Lustre is still loaded on the old net. Unmount first:\n"
            f"    ltvm llmount {node_name} --cleanup",
        )
    return node_name, 0, "ok"


def _load_cfg_profiles(cfg_dir: Path) -> list[tuple[str, str]]:
    """Read every ``*.sh`` auster profile out of *cfg_dir*.

    Returns [(cfg_name_without_suffix, content), ...] sorted by name.
    Dies on anything an operator would want to know about before a
    deploy starts: a bad path, an empty directory, or a profile named
    ``local.sh`` (which would clobber the tree's local.sh and the
    cluster block ltvm puts in it).
    """
    if not cfg_dir.is_dir():
        die(f"--cfg-dir: '{cfg_dir}' is not a directory")

    profiles = []
    for path in sorted(cfg_dir.glob("*.sh")):
        if path.name == "local.sh":
            die(
                f"--cfg-dir: '{path}' would clobber the generated cluster "
                "block in local.sh. Source it from your "
                "profile instead of replacing it."
            )
        try:
            content = path.read_text()
        except OSError as e:
            die(f"--cfg-dir: cannot read '{path}': {e}")
        profiles.append((path.stem, content))

    if not profiles:
        die(f"--cfg-dir: no *.sh config profiles in '{cfg_dir}'")
    return profiles


def _parallel_cluster_op(
    nodes: list,
    submit: Any,
    success_verb: str,
    failure_verb: str,
) -> list[str]:
    """Fan out ``submit(node)`` across a thread pool and collect results.

    Each submitted future must return a ``(name, rc, output)`` tuple.
    Prints per-node progress and returns the list of failed node names
    so the caller can decide whether to die() or continue.
    """
    failed: list[str] = []
    with ThreadPoolExecutor(max_workers=len(nodes)) as executor:
        futures = {executor.submit(submit, node): node for node in nodes}
        for future in as_completed(futures):
            node = futures[future]
            try:
                name, rc, output = future.result()
            except Exception as e:
                # _deploy_one_node can raise past its own except
                # RuntimeError -- VMInfo.load raises VMNotFound, which
                # is not a RuntimeError -- and an unguarded result()
                # aborted the whole fan-out with a Python traceback:
                # no per-node report, no "deploy failed for: ...",
                # update_deploy never recorded, local.sh never
                # distributed.  cmd_cluster_create already wraps its
                # result() for exactly this reason.
                name = getattr(node, "name", str(node))
                print(f"\n--- {name}: {failure_verb} ---\n{e}")
                failed.append(name)
                continue
            if rc != 0:
                print(f"\n--- {name}: {failure_verb} (rc={rc}) ---\n{output}")
                failed.append(name)
            else:
                print(f"  {name}: {success_verb}")
    return failed


def _validate_lustre_source(path: Path) -> None:
    """Die with a clear message if path is not a Lustre source tree.

    Only checks that the directory looks like a Lustre tree.
    Cluster deploy runs `ltvm build lustre` itself, so a freshly
    cloned tree (no .ko files yet) is valid input.
    """
    if not path.is_dir():
        die(f"--build:'{path}' is not a directory")

    missing = [
        name
        for name in ("configure.ac", "lustre", "lnet")
        if not (path / name).exists()
    ]
    if missing:
        die(
            f"--build:'{path}' does not look like a Lustre "
            f"source tree (missing: {', '.join(missing)})"
        )


@dataclass(frozen=True)
class ClusterBuildParams:
    """The build inputs a cluster's nodes actually run.

    All nodes in a cluster share one target, so these come from the
    first node's recorded metadata rather than from the target's
    defaults -- a target's default kernel is frequently not the kernel a
    given cluster was created with.
    """

    target: str
    os_family: str
    kernel: str | None
    arch: str
    variant: str = "base"


def cluster_build_params(cluster: ClusterInfo) -> ClusterBuildParams:
    """Resolve target, os_family, kernel and arch for *cluster*.

    Shared by `cluster deploy` and by `build lustre --for-cluster`, so a
    build aimed at a cluster cannot disagree with the deploy that
    follows it.
    """
    os_family = "rhel"
    target = DEFAULT_TARGET
    kernel_name: str | None = None
    arch = "x86_64"

    nodes = cluster.get_nodes()
    try:
        first_vm = VMInfo.load(nodes[0].name)
    except (VMNotFound, IndexError) as e:
        die(f"cluster {cluster.name!r}: cannot load first node: {e}")
    if first_vm.os_id:
        from .target_config import TargetConfig

        target = first_vm.os_id
        # Let ValueError from TargetConfig propagate up with a clear
        # error.  Previously a broad `except (..., ValueError, ...): pass`
        # silently fell back to DEFAULT_TARGET, which deployed rocky9 .ko
        # files onto whatever the cluster actually ran.
        try:
            os_family = TargetConfig(
                target, arch=first_vm.arch or None
            ).os_family
        except ValueError as e:
            die(f"cluster {cluster.name!r}: target {target!r}: {e}")
    if first_vm.kernel:
        # vm.kernel points at .../kernels/<name>/vmlinuz; extract <name>
        kernel_name = Path(first_vm.kernel).parent.name
    if first_vm.arch:
        arch = first_vm.arch

    return ClusterBuildParams(
        target=target,
        os_family=os_family,
        kernel=kernel_name,
        arch=arch,
        variant=first_vm.variant,
    )


def _resolve_deploy_net(
    cluster: ClusterInfo, requested: str | None
) -> ClusterNet:
    """Decide which LNet net this deploy configures, and resolve it.

    ``--net`` wins; without it the cluster keeps the net it was last
    deployed with, and a cluster that has never been deployed with one
    gets tcp -- the net every generated config used before ``--net``
    existed.

    Dies before any node is touched: a cluster left half-configured for
    two different nets is worse than one left alone.
    """
    net_type = requested or cluster.net or "tcp"
    if requested is None and not cluster.net and has_passthrough(cluster):
        die(
            f"cluster {cluster.name!r} has a passthrough NIC and no "
            f"recorded net; pass --net explicitly so deploy does not "
            f"overwrite the lnet.conf its HCA was configured with"
        )
    try:
        return resolve_net(cluster, net_type)
    except NetUnavailable as e:
        die(f"cluster {cluster.name!r} cannot run --net {net_type}: {e}")
        raise AssertionError("unreachable")


def cmd_cluster_deploy(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    nodes = cluster.get_nodes()
    src = Path(args.lustre_tree).expanduser().resolve()
    _validate_lustre_source(src)
    build = str(src)
    vm_claim.require_all([n.name for n in nodes], "deploy to")
    try:
        for n in nodes:
            vm_claim.auto_claim(n.name, build)
    except vm_claim.ClaimHeld as e:
        die(str(e))

    # Read the profiles up front: a typo in --cfg-dir should not cost a
    # whole deploy before it is reported.
    cfg_dir_arg = getattr(args, "cfg_dir", None)
    cfg_profiles: list[tuple[str, str]] = []
    if cfg_dir_arg:
        cfg_profiles = _load_cfg_profiles(
            Path(cfg_dir_arg).expanduser().resolve()
        )

    # Resolve the net before anything is deployed: an unrunnable net is
    # an argument error, not a half-configured cluster.
    net = _resolve_deploy_net(cluster, getattr(args, "net", None))

    params = cluster_build_params(cluster)
    os_family = params.os_family
    target = params.target
    kernel_name = params.kernel
    arch = params.arch

    print(f"=== Deploying to cluster '{cluster.name}' ===")
    print(f"    Lustre tree: {build}")

    # Deploy never builds.  Build options live on `build lustre` alone,
    # so a deploy that shelled out to it had to mirror every one of them
    # by hand and silently dropped --configure -- which shipped a cluster
    # without ko2iblnd and reported success.
    if kernel_name is None:
        die(
            f"cluster {cluster.name!r}: cannot resolve the node kernel; "
            f"recreate the cluster"
        )
    status = staging_status(
        build, target, arch=arch, kernel=kernel_name,
        variant=params.variant,
    )
    if not status.usable:
        die(
            f"no usable Lustre staging for {cluster.name} "
            f"({target}/{arch}/{kernel_name}): {status.reason}\n"
            f"  looked in: {status.path}\n"
            f"  build it first:\n"
            f"    {status.build_command(cluster=cluster.name)}"
        )

    print(f"    Staging: {status.path}")

    # FSTYPE is a deploy-time choice written into local.sh; whether ZFS
    # is available is the staged build's.  Every node shares one
    # target+kernel+arch, so resolve the ZFS to ship once, from the
    # staging meta -- osd_zfs.ko is linked against one specific build.
    fstype = getattr(args, "fstype", None) or "ldiskfs"
    zfs_staging: Path | None = None
    meta = read_staging_meta(status.path)
    staged_zfs = meta.get("zfs_version") if isinstance(meta, dict) else None
    if staged_zfs:
        from .target_config import TargetConfig
        from .zfs_build import zfs_staging_dir

        tc = TargetConfig(target, arch=arch, variant=status.variant)
        zfs_staging = zfs_staging_dir(tc, kernel_name, staged_zfs)
        if not any((zfs_staging / "lib" / "modules").rglob("zfs.ko*")):
            die(
                f"Lustre was built against ZFS {staged_zfs} but its "
                f"build artifact is missing from {zfs_staging}"
            )
        print(f"    ZFS: {staged_zfs}")
    elif fstype == "zfs":
        die(
            f"--fstype zfs, but the staging for {cluster.name} was not "
            f"built with ZFS\n"
            f"  build it first:\n"
            f"    {status.build_command(cluster=cluster.name)} --zfs"
        )
    print(f"    Deploying to {len(nodes)} nodes in parallel...")

    # Deploy to all nodes in parallel -- same as single-node deploy,
    # just run concurrently.
    failed = _parallel_cluster_op(
        nodes,
        lambda node: _deploy_one_node(node.name, build, os_family, zfs_staging),
        success_verb="deployed",
        failure_verb="FAILED",
    )

    if failed:
        die(f"deploy failed for: {', '.join(failed)}")

    # Record successful deploys on each VMInfo so `ltvm list` shows
    # last_deploy/build_path/kver -- single-node cmd_deploy does this
    # at the end of its flow; cluster deploy was missing it.
    import time as _time

    _now = int(_time.time())
    unrecorded: list[str] = []
    for node in nodes:
        try:
            vm = VMInfo.load(node.name)
            vm.update_deploy(_now, build, vm.kver)
        except VMNotFound:
            pass
        except PermissionError:
            # Same as single-node deploy: cluster deploy is unprivileged
            # and update_deploy never prompts, so a root-owned sockets/
            # without cached sudo costs only the bookkeeping.
            unrecorded.append(node.name)
    if unrecorded:
        print(
            f"  Warning: deploy metadata not recorded for "
            f"{', '.join(unrecorded)} (sockets dir is root-owned and "
            f"sudo needs a password); the deploy itself succeeded.",
            file=sys.stderr,
        )

    # After each node's own disk block, so the cluster topology wins.
    local_sh = generate_local_sh(
        cluster, net, os_family=os_family, fstype=fstype
    )
    print(f"\n--- Distributing cluster config (net {net.net_name})...")
    print(local_sh)

    ssh_opts = SSH_OPTS
    try:
        node_ips = {node.name: VMInfo.load(node.name).ip for node in nodes}
    except VMNotFound as e:
        die(f"cluster node missing: {e}")

    # Drop a stale LNet BEFORE writing either config file.  A node that
    # cannot unload keeps serving the old net whatever the files say, so
    # writing first would leave every node reconfigured for a net the
    # deploy then failed to reach -- config naming one net, cluster state
    # naming the other.  Unloading first costs nothing when it fails: the
    # node keeps the config it already had.
    failed_unload = _parallel_cluster_op(
        nodes,
        lambda node: _drop_stale_lnet(
            node.name, node_ips[node.name], net.net_type
        ),
        success_verb=f"LNet ready for {net.net_type}",
        failure_verb="LNet still on the old net",
    )
    if failed_unload:
        die(
            f"cannot move to net {net.net_type} while Lustre is loaded "
            f"on: {', '.join(failed_unload)}; no node was changed"
        )

    # lnet.conf goes out first and local.sh immediately after, from the
    # one resolved net.  A node holding one without the other names two
    # different networks and fails to mount with `no connections
    # available: rc = -22`, which reads as a Lustre fault.
    failed_lnet = _parallel_cluster_op(
        nodes,
        lambda node: _write_lnet_conf(
            node.name,
            node_ips[node.name],
            net.lnet_conf(node.name),
        ),
        success_verb="lnet.conf written",
        failure_verb="lnet.conf FAILED",
    )
    if failed_lnet:
        die(f"lnet.conf distribution failed for: {', '.join(failed_lnet)}")

    failed_sh = _parallel_cluster_op(
        nodes,
        lambda node: _write_cluster_local_sh(
            node.name,
            node_ips[node.name],
            local_sh,
            ssh_opts,
            os_family,
        ),
        success_verb="local.sh written",
        failure_verb="local.sh FAILED",
    )

    if failed_sh:
        die(f"local.sh distribution failed for: {', '.join(failed_sh)}")

    # Profiles go out after local.sh, so a profile that sources it finds
    # it already in place.
    if cfg_profiles:
        names = ", ".join(f"{n}.sh" for n, _ in cfg_profiles)
        print(f"\n--- Distributing config profiles from {cfg_dir_arg}: {names}")
        for cfg_name, content in cfg_profiles:
            failed_cfg = _parallel_cluster_op(
                nodes,
                lambda node, _n=cfg_name, _c=content: _write_cluster_cfg(
                    node.name,
                    node_ips[node.name],
                    _n,
                    _c,
                    ssh_opts,
                    os_family,
                ),
                success_verb=f"{cfg_name}.sh written",
                failure_verb=f"{cfg_name}.sh FAILED",
            )
            if failed_cfg:
                die(
                    f"{cfg_name}.sh distribution failed for: "
                    f"{', '.join(failed_cfg)}"
                )

    # Persist the net only once both files are on every node, so the
    # recorded net always describes what the nodes actually hold.
    if cluster.net != net.net_type:
        cluster.net = net.net_type
        try:
            cluster.save()
        except OSError as e:
            print(f"    warning: cannot record net={net.net_type}: {e}")

    print(f"\n=== Cluster '{cluster.name}' deployed (net {net.net_type}) ===")
    print(f"    mount it with: ltvm cluster llmount {cluster.name}")


def _run_llmount(
    cluster: ClusterInfo,
    os_family: str,
    *,
    cleanup: bool = False,
    server_only: bool = False,
    timeout: int = 300,
) -> None:
    """Run llmount.sh, or with ``cleanup`` llmountcleanup.sh, for the cluster.

    The cluster block in cfg/local.sh names every node, so the one run
    brings the whole cluster up or down, remote module loads included.
    It runs on the first client, the node that block treats as local: run
    anywhere else, llmount.sh also mounts a client there that
    llmountcleanup.sh never unmounts, and lustre_rmmod then fails on it.
    """
    clients = cluster.client_nodes()
    node = clients[0] if clients else cluster.mgs_node()
    node_vm = VMInfo.load(node.name)
    lustre_dir = lustre_libdir(os_family)
    script = "llmountcleanup.sh" if cleanup else "llmount.sh"
    cmd = f"cd {lustre_dir}/tests && LUSTRE={lustre_dir} bash {script}"
    if cleanup:
        cmd += " && lustre_rmmod"
    elif server_only:
        cmd += " --server-only"

    print(f"Running {script} from {node.name}...", flush=True)
    try:
        r = run(
            sshpass_ssh_argv(node_vm.ip, cmd),
            capture_output=False,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as e:
        die(
            f"{script} timed out after {e.timeout}s on {node.name}\n"
            f"  check `ssh {node.name} dmesg` and "
            f"`ltvm cluster exec {cluster.name} mds 'lctl dl'`",
            EXIT_TIMEOUT,
        )
    if r.returncode != 0:
        die(f"{script} failed (rc={r.returncode})")


def cmd_cluster_llmount(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    vm_claim.require_all(
        [n.name for n in cluster.get_nodes()],
        "unmount" if getattr(args, "cleanup", False) else "mount",
    )
    down = [n.name for n in cluster.get_nodes() if _node_state(n.name) != "up"]
    if down:
        die(
            f"cluster '{cluster.name}' has nodes not running: "
            f"{', '.join(down)}\n"
            f"  start them with: ltvm cluster start {cluster.name}",
            EXIT_UNREACHABLE,
        )
    from .vm_commands import _os_family_for_vm

    mgs_vm = VMInfo.load(cluster.mgs_node().name)
    _run_llmount(
        cluster,
        _os_family_for_vm(mgs_vm, "libdir"),
        cleanup=args.cleanup,
        server_only=args.server_only,
        timeout=args.timeout,
    )


def cmd_cluster_destroy(args: argparse.Namespace) -> None:
    # Nodes go through the single-VM destroy, so a cluster node is torn
    # down exactly as `ltvm destroy <node>` would do it.
    from .vm_commands import cmd_destroy

    for name in args.names:
        try:
            cluster = ClusterInfo.load(name)
        except ClusterNotFound:
            # Match `ltvm destroy`: a name that is already gone is not
            # an error, so a cleanup script can run it unconditionally.
            print(f"destroy: cluster {name} not found")
            continue
        vm_claim.require_all([n.name for n in cluster.get_nodes()], "destroy")
        print(f"=== Destroying cluster '{cluster.name}' ===")
        cmd_destroy(
            argparse.Namespace(
                names=[n.name for n in cluster.get_nodes()],
                drop_cluster_records=False,
            )
        )
        cluster.path.unlink(missing_ok=True)
        print(f"=== Cluster '{cluster.name}' destroyed ===")


def _node_state(name: str) -> str:
    """ "up" / "down" / "missing" / "corrupt" for one cluster member.

    ValueError is VMInfo.load's deliberate failure on a truncated or
    hand-edited .info; one casualty must not take out a whole listing.
    """
    try:
        return "up" if is_running(VMInfo.load(name)) else "down"
    except VMNotFound:
        return "missing"
    except ValueError:
        return "corrupt"


def cmd_cluster_list(args: argparse.Namespace) -> None:
    use_json = bool(getattr(args, "json", False))
    clusters: list[dict[str, Any]] = []
    for cname in ClusterInfo.all_names():
        try:
            cluster = ClusterInfo.load(cname)
        except ClusterNotFound:
            # Race: .cluster file disappeared between all_names() and load().
            continue
        except (RuntimeError, ValueError) as e:
            # Corrupt or malformed cluster file -- flag it and keep
            # listing the rest rather than crashing.  Better to see
            # "clusterA: <BROKEN: ...>" than to get nothing at all.
            clusters.append({"cluster": cname, "error": str(e)})
            continue
        clusters.append(
            {
                "cluster": cname,
                "owner_id": cluster.owner_id,
                "nodes": [
                    {
                        "name": n.name,
                        "roles": list(n.roles),
                        "state": _node_state(n.name),
                    }
                    for n in cluster.get_nodes()
                ],
            }
        )

    if use_json:
        print(json.dumps({"clusters": clusters}, indent=2))
        return
    if not clusters:
        print("(no clusters)")
        return
    for c in clusters:
        if "error" in c:
            print(f"{c['cluster']}: <BROKEN: {c['error']}>")
            continue
        summary = " ".join(
            f"{n['name']}({'+'.join(n['roles'])},{n['state']})"
            for n in c["nodes"]
        )
        print(f"{c['cluster']}: {summary} owner={c['owner_id'] or '-'}")


# What a Lustre build has to match.  One staging tree serves a cluster
# only if every node agrees on all three, so they are reported together.
IDENTITY_FIELDS = ("target", "arch", "kernel")


def node_identities(names: list[str]) -> dict[str, dict[str, str]]:
    """Map node name to the target/arch/kernel its VM state records.

    A node with no VM state contributes an empty mapping rather than
    raising: status must stay usable when one node has been destroyed.
    """
    out: dict[str, dict[str, str]] = {}
    for name in names:
        try:
            vm = VMInfo.load(name)
        except VMNotFound:
            out[name] = {}
            continue
        out[name] = {
            "target": vm.os_id,
            "arch": vm.arch,
            "kernel": vm.kver,
        }
    return out


def identity_summary(
    identities: dict[str, dict[str, str]],
) -> tuple[dict[str, str], dict[str, dict[str, str]]]:
    """Split node identities into what they agree on and what they do not.

    Returns ``(agreed, divergent)``.  ``agreed`` carries one value per
    field where every node that reports one reports the same.
    ``divergent`` maps a field to ``{node: value}`` where they differ --
    a build then matches at most one node, and the rest fail at insmod,
    far from the build that chose the kernel.

    Nodes missing a value are ignored rather than counted as a
    disagreement; a destroyed node is absent, not contradictory.
    """
    agreed: dict[str, str] = {}
    divergent: dict[str, dict[str, str]] = {}
    for f in IDENTITY_FIELDS:
        seen = {n: i[f] for n, i in identities.items() if i.get(f)}
        values = set(seen.values())
        if len(values) == 1:
            agreed[f] = values.pop()
        elif len(values) > 1:
            divergent[f] = seen
    return agreed, divergent


def cmd_cluster_status(args: argparse.Namespace) -> None:
    use_json = bool(getattr(args, "json", False))
    cluster = ClusterInfo.load(args.name)
    nodes = cluster.get_nodes()
    rows = [
        {
            "name": node.name,
            "ip": node.ip,
            "state": _node_state(node.name),
            "roles": list(node.roles),
            "mdt_disks": node.mdt_disks,
            "ost_disks": node.ost_disks,
            "mgs_disk": bool(node.is_mgs and not node.is_mds),
        }
        for node in nodes
    ]

    if use_json:
        print(
            json.dumps(
                {
                    "cluster": cluster.name,
                    "owner_id": cluster.owner_id,
                    "nodes": rows,
                },
                indent=2,
            )
        )
        return

    print(f"cluster: {cluster.name}")
    print(f"owner:   {cluster.owner_id or '-'}")
    print(f"nodes:   {len(nodes)}")

    agreed, divergent = identity_summary(
        node_identities([n.name for n in nodes])
    )
    # These four are what a build and a deploy have to match, so they
    # belong next to the node list rather than behind `cluster exec
    # uname -r` on every node.
    print(f"target:  {agreed.get('target') or '-'}")
    print(f"arch:    {agreed.get('arch') or '-'}")
    print(f"kernel:  {agreed.get('kernel') or '-'}")
    if cluster.net:
        print(f"net:     {cluster.net}")
    else:
        print("net:     tcp (default; never deployed)")

    for f, per_node in divergent.items():
        detail = " ".join(f"{n}={v}" for n, v in sorted(per_node.items()))
        print(
            f"warning: nodes disagree on {f}: {detail}\n"
            f"         one Lustre build can serve at most one of these",
            file=sys.stderr,
        )

    print()

    # The human path walks the nodes, not `rows`: a dict of mixed value
    # types comes back out as `object`, and "+".join(object) is not a
    # thing mypy will accept -- nor should it.
    for node in nodes:
        status = "running" if _node_state(node.name) == "up" else "stopped"
        disks = ""
        if node.mdt_disks:
            disks += f" mdt={node.mdt_disks}"
        if node.ost_disks:
            disks += f" ost={node.ost_disks}"
        if node.is_mgs and not node.is_mds:
            disks += " mgs=1"
        roles = "+".join(node.roles)
        print(
            f"  {node.name:<20} {node.ip:<18} {status:<8} {roles:<12}{disks}",
        )


def cmd_cluster_ssh(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    target = args.target
    nodes = cluster.get_nodes()

    # ssh opens one interactive session, so a role selects its first
    # node (unlike `cluster exec`, which fans out).  Prefer an exact
    # node-name match so an explicit name is never shadowed by a role.
    exact = [n for n in nodes if n.name == target]
    by_role = [n for n in nodes if target in n.roles]
    candidates = exact or by_role
    matched = candidates[0] if candidates else None
    if matched is None:
        die(
            f"no node matching '{target}' in cluster '{args.name}'",
        )
        raise AssertionError("unreachable")

    vm = VMInfo.load(matched.name)
    ssh_args = [
        "sshpass",
        "-p",
        ROOT_PASSWORD,
        "ssh",
        *SSH_OPTS,
        f"root@{vm.ip}",
        *args.command,
    ]
    os.execvp("sshpass", ssh_args)


def cmd_cluster_exec(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    target = args.target
    nodes = cluster.get_nodes()

    # A role names every node holding it.  Running on only the first
    # match reported one OSS out of three and exited 0, which reads as
    # "the whole role is healthy" -- and the docs describe this exact
    # command as "run a command on all OSS nodes".  An exact node name
    # still selects exactly that node.
    exact = [n for n in nodes if n.name == target]
    matches = exact or [n for n in nodes if target in n.roles]
    if not matches:
        die(
            f"no node matching '{target}' in cluster '{args.name}'",
        )
        raise AssertionError("unreachable")

    # Two idioms the user might type:
    #   ltvm cluster exec co2 oss 'lctl dl'     -> argv=['lctl dl']
    #   ltvm cluster exec co2 oss lctl dl       -> argv=['lctl', 'dl']
    #
    # shlex.join unconditionally quotes each arg, so the first form
    # becomes "'lctl dl'" -- a single shell token the remote bash
    # reads as a command name containing a space ("lctl dl: command
    # not found", rc=127).  When the argv is already one pre-joined
    # shell string (the user did the quoting), pass it verbatim;
    # otherwise safely quote each argv element so spaces / globs /
    # quotes inside individual args survive transport.
    if len(args.command) == 1:
        command = args.command[0]
    else:
        command = shlex.join(args.command)
    use_json = bool(getattr(args, "json", False))
    multi = len(matches) > 1
    worst = 0
    # Under --json the per-node output is collected and emitted as one
    # document at the end rather than streamed: a caller parsing stdout
    # cannot use a stream of remote command output interleaved with
    # "--- node ---" separators.  The human path is unchanged, and
    # still streams.
    results: list[dict[str, Any]] = []
    vm_claim.require_all([n.name for n in matches], "run commands on")
    for node in matches:
        vm = VMInfo.load(node.name)
        if multi and not use_json:
            print(f"--- {node.name} ---")
        try:
            r = run_ssh(vm.ip, command, timeout=args.timeout)
        except subprocess.TimeoutExpired:
            if not multi and not use_json:
                die(f"timeout after {args.timeout}s", EXIT_TIMEOUT)
            results.append(
                {
                    "node": node.name,
                    "rc": EXIT_TIMEOUT,
                    "timed_out": True,
                    "stdout": "",
                    "stderr": f"timeout after {args.timeout}s",
                }
            )
            if not use_json:
                print(
                    f"{node.name}: timeout after {args.timeout}s",
                    file=sys.stderr,
                )
            worst = EXIT_TIMEOUT
            continue
        results.append(
            {
                "node": node.name,
                "rc": r.returncode,
                "timed_out": False,
                "stdout": r.stdout or "",
                "stderr": r.stderr or "",
            }
        )
        if not use_json:
            if r.stdout:
                print(r.stdout, end="")
            if r.stderr:
                print(r.stderr, end="", file=sys.stderr)
        # Exit non-zero if any node did; a role-wide command that
        # failed somewhere must not look like a clean run.
        if r.returncode != 0 and worst == 0:
            worst = r.returncode
    if use_json:
        print(
            json.dumps(
                {
                    "cluster": args.name,
                    "target": target,
                    "command": command,
                    "rc": worst,
                    "nodes": results,
                },
                indent=2,
            )
        )
    sys.exit(worst)
